import { NavItem, Project, Service, AboutContent } from './types';

// Hero Cover Image - The main background image behind the hero text
export const HERO_IMAGE_URL = '/images/hero/hero-cover.jpg.jpeg'; // Put your hero image in public/images/hero/

// Logo - Replace the text logo in navbar
export const LOGO_URL = '/images/logo/logo.png'; // Put your logo PNG in public/images/logo/

export const NAV_ITEMS: NavItem[] = [
  { label: 'About Us', href: '#about' },
  { label: 'Services', href: '#services' },
  { label: 'Portfolio', href: '#portfolio' },
];

export const ABOUT_CONTENT: AboutContent = {
  imageUrl: '/images/about/about-hero.jpg', // Put your image in public/images/about/
  imageAlt: 'Architectural Detail',
  heading: 'Architecture for a',
  headingHighlight: 'world that refuses',
  description: 'Mukherji Architects operates at the intersection of intelligent design and intelligent technology. We refine how we work continuously - not yearly, not monthly - because better decisions come from better systems.',
  philosophy: "We don't rely on intuition or guesswork. We interrogate ideas, test more options, and design with a level of precision that reduces risk and improves performance across the entire project lifecycle."
};

// Dynamically load projects and services from generated files
// These are generated by scripts/generate-projects.js from the folder structure
// Run "npm run generate" to scan the projects folder and regenerate these imports

// Import generated data (created by generate-projects.js script)
// Using dynamic imports that work with Vite's build system
import { PROJECTS as GENERATED_PROJECTS } from './generated/projects';
import { SERVICES as GENERATED_SERVICES } from './generated/services';

// Export projects - populated from folder structure
export const PROJECTS: Project[] = GENERATED_PROJECTS;

// Export services - populated from folder structure  
export const SERVICES: Service[] = GENERATED_SERVICES;
